#!/usr/bin/env python3
"""
Extract the highest accuracy for each method from matrix results.
This script reads the best_cost_savings_matrix.json files generated by --matrix-only option.
"""

import json
import sys
from pathlib import Path
from typing import Dict, Optional

# Datasets to check
DATASETS = ["cuad", "blackvault", "game_reviews", "sustainability", "biodex", "medec", "facility"]

def extract_highest_accuracies_from_matrix(matrix_file: Path) -> Optional[Dict[str, float]]:
    """
    Extract highest accuracy for each method from a matrix JSON file.
    
    Args:
        matrix_file: Path to best_cost_savings_matrix.json
        
    Returns:
        Dictionary mapping method names to their highest accuracy, or None if file doesn't exist
    """
    if not matrix_file.exists():
        return None
    
    try:
        with open(matrix_file, 'r') as f:
            data = json.load(f)
        
        method_info = data.get("method_info", {})
        accuracies = {}
        
        for method, info in method_info.items():
            best_accuracy = info.get("best_accuracy")
            if best_accuracy is not None:
                accuracies[method] = best_accuracy
        
        return accuracies
    except Exception as e:
        print(f"Error reading {matrix_file}: {e}", file=sys.stderr)
        return None

def find_matrix_files(base_dir: Path) -> Dict[str, Dict[str, float]]:
    """
    Find all matrix files and extract highest accuracies for each dataset.
    
    Args:
        base_dir: Base directory to search for matrix files
        
    Returns:
        Dictionary mapping dataset names to method accuracies
    """
    results = {}
    
    for dataset in DATASETS:
        # Check in outputs/{dataset}_original_final/best_cost_savings_matrix.json
        matrix_file = base_dir / "outputs" / f"{dataset}_original_final" / "best_cost_savings_matrix.json"
        
        accuracies = extract_highest_accuracies_from_matrix(matrix_file)
        if accuracies:
            results[dataset] = accuracies
    
    return results

def print_results(results: Dict[str, Dict[str, float]]):
    """Print the results in a formatted way."""
    if not results:
        print("No matrix files found. Please run with --matrix-only first.")
        return
    
    # Collect all methods across all datasets
    all_methods = set()
    for dataset_results in results.values():
        all_methods.update(dataset_results.keys())
    
    # Sort methods in desired order
    desired_order = ["mcts", "original", "simple_baseline", "lotus", "LOTUS_d", "LOTUS_r&r", "PZ_direct", "PZ_retrieval", "PZ"]
    methods = []
    for method in desired_order:
        if method in all_methods:
            methods.append(method)
    # Add any remaining methods
    for method in sorted(all_methods):
        if method not in methods:
            methods.append(method)
    
    print("\n" + "="*80)
    print("HIGHEST ACCURACY FOR EACH METHOD (from --matrix-only results)")
    print("="*80)
    print()
    
    # Print header
    header = f"{'Method':<20}"
    for dataset in sorted(results.keys()):
        header += f"{dataset:>15}"
    print(header)
    print("-" * len(header))
    
    # Print each method's accuracies
    for method in methods:
        row = f"{method:<20}"
        for dataset in sorted(results.keys()):
            accuracy = results[dataset].get(method)
            if accuracy is not None:
                row += f"{accuracy:>15.4f}"
            else:
                row += f"{'N/A':>15}"
        print(row)
    
    print()
    print("="*80)
    print("SUMMARY: Highest accuracy across all datasets for each method")
    print("="*80)
    print()
    
    for method in methods:
        accuracies = []
        for dataset_results in results.values():
            if method in dataset_results:
                accuracies.append(dataset_results[method])
        
        if accuracies:
            max_accuracy = max(accuracies)
            print(f"{method:<20} {max_accuracy:>10.4f}")
        else:
            print(f"{method:<20} {'N/A':>10}")

def main():
    # Try to find matrix files in current directory or common locations
    base_dirs = [
        Path.cwd(),
        Path.cwd() / "outputs",
        Path("/tmp/modal"),
    ]
    
    results = {}
    for base_dir in base_dirs:
        if base_dir.exists():
            found_results = find_matrix_files(base_dir)
            if found_results:
                results.update(found_results)
                break
    
    # If no results found, check Modal volume mount path
    if not results:
        # Check if we can access Modal volume
        modal_paths = [
            Path("/tmp/modal"),
            Path.home() / ".modal",
        ]
        for modal_path in modal_paths:
            if modal_path.exists():
                found_results = find_matrix_files(modal_path)
                if found_results:
                    results.update(found_results)
                    break
    
    print_results(results)
    
    # Also try to run the matrix generation if no results found
    if not results:
        print("\n⚠️  No existing matrix files found.")
        print("   To generate matrices, run:")
        print("   python -m experiments.reasoning.run_test_frontier --matrix-only --dataset all")
        print("\n   Or for a specific dataset:")
        print("   python -m experiments.reasoning.run_test_frontier --matrix-only --dataset cuad")

if __name__ == "__main__":
    main()

